#!/usr/bin/python

#
# curl -s -L -H "X-Cisco-Meraki-API-Key: $apikey" -X GET -H 'Content-Type: application/json' 'https://dashboard.meraki.com/api/v0/organizations' | jq '.'
#
#

import getopt, sys, os, os.path
import json
import yaml
import re
import requests

verbose = False
apikey = ''
orgid = ''
networkToList = ''
configfile = '/usr/local/etc/meraki.yaml'
addsubnet = False
subnet = ''
subnetname = ''
gateway = ''

def getJson(key, url):

    headers = {}
    headers['Content-Type'] = 'application/json'
    headers['X-Cisco-Meraki-API-Key'] = key

    try:
        r = requests.get(url, headers=headers)
    except requests.exceptions.RequestException as e:
        print "Error: %s" % (e)
        return False

    if verbose:
        print "r.status_code = %s" % (r.status_code)
        print "r.text = %s" % (r.text)

    if r.status_code == 404:
        print "404 Not found: %s" % (url)
        return False
    if r.status_code != 200:
        print "Error: %s - %s" % (r.status_code, r.text)
        return False

    data = json.loads(r.text)

    return data

def postJson(key, url, parameters):

    headers = {}
    headers['Content-Type'] = 'application/json'
    headers['X-Cisco-Meraki-API-Key'] = key

    try:
        r = requests.post(url, json=parameters, headers=headers)
    except requests.exceptions.RequestException as e:
        print "Error: %s" % (e)
        return False

    if verbose:
        print "r.status_code = %s" % (r.status_code)
        print "r.text = %s" % (r.text)

    if r.status_code == 404:
        print "404 Not found: %s" % (url)
        return False
    if r.status_code != 201:
        print "Error: %s - %s" % (r.status_code, r.text)
        return False
    return True

# Devices

def getDevices(key, networkId):
    url = "https://dashboard.meraki.com/api/v0/networks/%s/devices" % (networkId)
    return getJson(key, url)

def getLldpCdp(key, networkId, serial):
    url = "https://dashboard.meraki.com/api/v0/networks/%s/devices/%s/lldp_cdp?timespan=7200" % (networkId, serial)
    return getJson(key, url)

# MX L3 firewall

def getL3FirewallRules(key, networkId):
    url = "https://dashboard.meraki.com/api/v0/networks/%s/l3FirewallRules" % (networkId)
    return getJson(key, url)

# Networks

def getNetworks(key, orgid):
    url = "https://dashboard.meraki.com/api/v0/organizations/%s/networks" % (orgid)
    return getJson(key, url)

def getSiteToSiteVpn(key, networkId):
    url = "https://dashboard.meraki.com/api/v0/networks/%s/siteToSiteVpn" % (networkId)
    return getJson(key, url)

def getSiteToSiteVpnSubnetsAsHash(key, networkId):
    siteToSiteVpns = getSiteToSiteVpn(key, networkId)
    hashed = {}
    for subnet in siteToSiteVpns['subnets']:
        hashed[subnet['localSubnet']] = subnet
    return hashed

# Organizations

def getOrganizations(key):
    url = "https://dashboard.meraki.com/api/v0/organizations"
    return getJson(key, url)

# Static routes

def getStaticRoutes(key, networkId):
    url = "https://dashboard.meraki.com/api/v0/networks/%s/staticRoutes" % (networkId)
    return getJson(key, url)

def addStaticRoute(key, networkId, subnet, subnetname, gatewayIp):
    url = "https://dashboard.meraki.com/api/v0/networks/%s/staticRoutes" % (networkId)
    parameters = {}
    parameters['name'] = subnetname
    parameters['subnet'] = subnet
    parameters['gatewayIp'] = gatewayIp
    parameters['enabled'] = True
    parameters['active'] = 'always'
    return postJson(key, url, parameters)

def findNetwork(apikey, orgid, networkName):
    networks = getNetworks(apikey, orgid)
    for network in networks:
        if verbose:
            print "Network: %s" % (network['name'])
        if network['name'].lower() == networkName.lower():
            return network
    return False

def listSiteToSiteVpn(key, orgid):
    if (len(networkToList) < 1):
        print "Please specify a network."
        return
    network = findNetwork(apikey, orgid, networkToList)
    if network is False:
        print "Unable to find network: %s" % (networkToList)
        return
    siteToSiteVpn = getSiteToSiteVpn(key, network['id'])
    for subnet in siteToSiteVpn['subnets']:
        print "%s,%s" % (subnet['localSubnet'], subnet['useVpn'])

def listL3FirewallRules(apikey, orgid):
    if (len(networkToList) < 1):
        print "Please specify a network."
        return
    network = findNetwork(apikey, orgid, networkToList)
    if network is False:
        print "Unable to find network: %s" % (networkToList)
        return
    l3FirewallRules = getL3FirewallRules(apikey, network['id'])
    line = 1
    for l3FirewallRule in l3FirewallRules:
        print "%d,%s,%s,%s,%s,%s,%s,'%s',%s" % (line, l3FirewallRule['policy'], l3FirewallRule['protocol'], \
            l3FirewallRule['srcCidr'], l3FirewallRule['srcPort'], \
            l3FirewallRule['destCidr'], l3FirewallRule['destPort'], \
            l3FirewallRule['comment'], l3FirewallRule['syslogEnabled'])
        line += 1

def listStaticRoutes(key, orgid):
    networks = getNetworks(apikey, orgid)
    for network in networks:
        if verbose:
            print "Network: %s" % (network['name'])

        if (len(networkToList) < 1) or \
                (networkToList.lower() == network['name'].lower()):
            staticRoutes = getStaticRoutes(apikey, network['id'])
            siteToSiteVpnSubnets = getSiteToSiteVpnSubnetsAsHash(key, network['id'])
            for staticRoute in staticRoutes:
                if verbose:
                    print "  staticRoute: %s" % (staticRoute)
                invpn = ''
                if staticRoute['subnet'] in siteToSiteVpnSubnets:
                    useVpn = siteToSiteVpnSubnets[staticRoute['subnet']]['useVpn']
                    if useVpn:
                        invpn = 'yes'
                    else:
                        invpn = 'no'

                print "%s,%s,'%s',%s,%s,%s" % (network['name'], staticRoute['subnet'], staticRoute['name'], staticRoute['gatewayIp'], staticRoute['enabled'], invpn)
            if len(networkToList):
                return

def listOrganizations(key):
    organizations = getOrganizations(key)
    if organizations == False:
        print "Unable to getOrganizations.  Wrong apikey?"
        return
    for organization in organizations:
        print "%s,'%s'" % (organization['id'], organization['name'])

def listNetworks(key, orgid):
    networks = getNetworks(key, orgid)
    if networks == False:
        print "Unable to getNetworks.  Wrong apikey?"
        return
    for network in networks:
        print "%s" % (network['name'])

def listLldpCdpCmd(key, orgid):
    print "In progress"
    networks = getNetworks(key, orgid)
    for network in networks:
        if verbose:
            print "Network: %s (%s)" % (network['name'], networkToList)

        if len(networkToList) and (networkToList <> network['name']):
            continue

        devices = getDevices(apikey, network['id'])
        for device in devices:
            if verbose:
                print " Device: %s" % (device['name'])
            lldpCdp = getLldpCdp(apikey, network['id'], device['serial'])
            print "lldpCdp=%s" % (lldpCdp)
            if 'ports' not in lldpCdp:
                continue
            for port in lldpCdp['ports']:
                if verbose:
                    print "  port: %s" % (port)
                for neighbor in lldpCdp['ports'][port]:
                    print "  neighbor: %s" % (neighbor)
#                print "%s,%s,'%s',%s,%s" % (network['name'], staticRoute['subnet'], staticRoute['name'], staticRoute['gatewayIp'], staticRoute['enabled'])
            if len(networkToList):
                return

# {u'sourceMac': u'e0:55:3d:7b:1f:3c', u'ports': {u'port3': {u'lldp': {u'sourcePort': u'port3', u'portId': u'gi4', u'systemName': u'TDP-BRO-SW01'}, u'cdp': {u'sourcePort': u'port3', u'portId': u'gi4', u'deviceId': u'046c9dd6c325', u'address': u'10.15.44.253'}}}}

def staticRoutesCmd(apikey, orgid):
    if addsubnet:
        if len(subnet) < 1:
            print "Missing subnet"
            sys.exit(5)
        p = re.compile('\d+\.\d+\.\d+\.\d+/\d+')
        if not p.match(subnet):
            print "Bad subnet format: %s" % (subnet)
            sys.exit(6)

        if len(subnetname) < 1:
            print "Missing subnet name"
            sys.exit(5)

        if len(gateway) < 1:
            print "Missing gateway"
            sys.exit(5)
        p = re.compile('\d+\.\d+\.\d+\.\d+')
        if not p.match(gateway):
            print "Bad gateway format: %s" % (gateway)
            sys.exit(61)

        if len(networkToList) < 1:
            print "Missing network"
            sys.exit(5)

        network = findNetwork(apikey, orgid, networkToList)
        if network == False:
            print "Cannot find network: " % (networkToList)
            sys.exit(7)
        if verbose:
            print " Network id = %s" % (network['id'])
        addStaticRoute(apikey, network['id'], subnet, subnetname, gateway)
    else:
        listStaticRoutes(apikey, orgid)

if 'MERAKI_APIKEY' in os.environ:
    apikey = os.environ['MERAKI_APIKEY']
if 'MERAKI_ORGID' in os.environ:
    orgid = os.environ['MERAKI_ORGID']

if len(sys.argv) < 2:
    print "Please provide a command: staticroutes cdp lldp"
    sys.exit(1)

options, remainder = getopt.getopt(sys.argv[2:], 's:v', ['add', 'apikey=',
                                                         'gateway=',
                                                         'name=', 'network=',
                                                         'orgid=',
                                                         'subnet=',
                                                         'verbose',
                                                         ])
for opt, arg in options:
    if opt in ('--add'):
        addsubnet = True
    elif opt in ('--apikey'):
        apikey = arg
    elif opt in ('--gateway'):
        gateway = arg
    elif opt in ('--name'):
        subnetname = arg
    elif opt in ('--network'):
        networkToList = arg
    elif opt in ('--orgid'):
        orgid = arg
    elif opt in ('-s', '--subnet'):
        subnet = arg
    elif opt in ('-v', '--verbose'):
        verbose = True

cmd = sys.argv[1]

if os.path.isfile(configfile):
    with open(configfile) as fp:
        configuration = yaml.load(fp)
        if 'apikey' in configuration:
            apikey = configuration['apikey']
        if 'orgid' in configuration:
            orgid = configuration['orgid']

if len(apikey) < 1:
    print "Missing apikey"
    sys.exit(3)

if len(orgid) < 1:
    organizations = getOrganizations(apikey)
    if organizations == False:
        print "Unable to getOrganizations.  Wrong apikey?"
        sys.exit(66)

    if len(organizations) > 1:
        print "APIKEY is associated with more than one orgid.  Please specify only one with --orgid."
        for organization in organizations:
            print "%s,'%s'" % (organization['id'], organization['name'])
        sys.exit(3)

    if len(orgid) < 1:
        orgid = organizations[0]['id']
    else:
        print "Unable to fetch orgid."
        sys.exit(4)

if cmd == "staticroutes":
    staticRoutesCmd(apikey, orgid)
elif (cmd == "lldp") or (cmd == "cdp"):
    listLldpCdpCmd(apikey, orgid)
elif cmd == "networks":
    listNetworks(apikey, orgid)
elif cmd == "organizations":
    listOrganizations(apikey)
elif cmd == "l3firewallrules":
    listL3FirewallRules(apikey, orgid)
elif cmd == "sitetositevpn":
    listSiteToSiteVpn(apikey, orgid)
else:
    print "Unknown command: %s" % (cmd)

